apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    app: db-deploy
  ports:
    - name: "postgres"
      protocol: TCP
      port: 5432
      targetPort: 5432
