apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy    
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.1-alpine
        ports:
        - containerPort: 80
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret-2
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret-2
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret-2
              key: database
